### PR TITLE
Add localizations of FormatOptions

### PR DESCRIPTION
**Pull request by mgold**
Spanish comes from the comments; the rest are from my library.

There are a number of places you can go from here:
* Including month and weekday abbreivations
* Including AM/PM translations
* Including number suffix translations (you don't say 1st in French)
* Including more languages
* Possibly using records instead of functions

But I think this is a good start.

### CODE REVIEW

**Review by ryan-haskell — COMMENTED** [review]
Hey Max,

I really like the direction of making this package more inclusive! I think that's incredibly important, but where do we draw the line on languages to include?

If someone requested German, shouldn't that be added in too?

I think it's useful to have documentation for how to configure your own language, but I'm not sure if the date-format package should be responsible for having all of these translations included.

My guess (with no data to support my claim 😄 ) is most people using this package will be displaying dates in a single language, meaning they will be downloading N-1 other languages they don't need.

Would it make more sense if this was a separate package to supplements this one? Like `date-format-languages`?

My instinct is to provide documentation on how the user can customize this for any language, that way no one feels "non-official" or left out!

I know that's a lot of feedback all at once, but I'm curious: what are your thoughts on this?

_Another side note_: The code looks great, but it looks like the Localized.elm file is only exposing `spanish`!

**Comment by mgold** [comment]
> most people using this package will be displaying dates in a single language, meaning they will be downloading N-1 other languages they don't need

That's a really great point. I think that some advanced websites could automatically or interactively select a language, and that would need to be loaded, stored in the model (an argument for records over functions), and so on. But most people will likely have one.

I think -- and we should confirm -- that 0.19 tree shaking is per function, so you don't pay (in bundle size) for what you don't use.

That still leaves the problem of "who gets to have an official language". I've accepted PRs from whomever bothered to submit one. There is also "how do we handle disagreements about what is correct". I know that French, Portuguese, and Spanish are spoken in both parts of Europe and parts of the Americas, with subtle differences; I don't know if they disagree on days of the week. Perhaps we'd need to use `en_US`-style codes (I don't know what those are called).

So maybe this needs to be done in phases: try to come up with the best interface for customization, with example languages that don't ship in the package. Then we add languages as requested.

>  it looks like the Localized.elm file is only exposing `spanish`

Oops!

**Comment by Augustin82** [comment]
We started using this lib (great work, btw) and we need to customize suffixes for French formats, like @mgold pointed out.

Is there any way to help, with this and with the PR/lib in general?

Cheers!

**Comment by ryan-haskell** [comment]
Glad to hear you like the library! 😄 

I completely agree with you both, we should move forward with the localization.

I'm thinking that a `2.0.0` might need to be released, where we:

1. Create `Language` in place of `FormatOptions`:

```elm
type alias Language =
    { toMonthName : Month -> String
    , toWeekdayName : Weekday -> String
    , toAmPm : Hour -> String
    , toSuffix : Int -> String
    }
```

2. Create a `DateFormat.Languages` module, with some common languages (like what Max did with `DateFormat.Localized`)

```elm
module DateFormat.Languages exposing (english, spanish, french)

english : Language
english = { ... }

spanish : Language
spanish = { ... }

french : Language
french = { ... }
```

3. `formatWithOptions` will become `formatWithLanguage` (that `format` uses behind the scenes)

```elm
formatWithLanguage : Language -> List Token -> Zone -> Posix -> String
formatWithLanguage language tokens zone posix =
   "..."

format : List Token -> Zone -> Posix -> String
format =
    formatWithLanguage DateFormat.Languages.english
```

---

@mgold - would this API design make sense to you? are there any things we should change?

@Augustin82  - are there any other additional fields besides AM/PM and suffix that you might need?


Let me know!
Ryan

**Comment by Augustin82** [comment]
I've asked my colleagues to give feedback about what else may be missing.

As for starting a new version, sure, great, let's go =)

**Comment by mgold** [comment]
I might call it `toOrdinalSuffix`. You may also need `toWeekdayAbbreviation` and `toMonthAbbreviation`. I would not assume that taking the first n characters will always work, even if you made n configurable by language. Would we want some way to configure AM/PM vs. 24 hour time?

Can confirm for my June self that 0.19 does per-function dead code removal, so there's no harm adding lots of languages.

I think it's a good idea to use functions instead of custom types (formerly union types) because it gives us flexibility.

It sounds like this might take a few drafts to get right before the major release.

Closing the PR but let's keep talking.

**Comment by ryan-haskell** [comment]
@mgold and @Augustin82 ,

Great suggestions, Max! I've updated the records to follow your naming convention.

There are some changes on `master` with the new `DateFormat.Language` module.

Let me know what you think!

Also, please feel free to add more languages.! It would be awesome to have French in there for the 2.0.0 release.

You can try it locally by following the README.md in the examples folder:
https://github.com/ryannhg/date-format/tree/master/examples

Thanks again,
Ryan

**Pull request closed without merging**
