### PR TITLE
Fix relative months calculation

### PR DESCRIPTION
**Pull request by felipehummel**
Hi! The calculation for the relative time regarding months is wrong: 

https://github.com/ryannhg/date-format/blob/master/src/DateFormat/Relative.elm#L187

There was no test for relative time regarding both months and years, so I added them.

PS: I'm using this in https://revisar.me and ~I'll try to contribute a Portuguese language pack after this~ Done: https://github.com/ryannhg/date-format/pull/16

### CODE REVIEW

**Comment by felipehummel** [comment]
@ryannhg fixed the bump conflict. I forgot that merging the other PR would impact this one 😁

**Comment by mgold** [comment]
In general, avoid bumping the package version when submitting PRs. But in this case it's probably fine to merge and release.

**Comment by felipehummel** [comment]
@mgold Good to know, it's my first contribution to an Elm package.

**Comment by ryan-haskell** [comment]
Hey @felipehummel !

Thank you so much for your contribution.

Sorry it took me a while to actually publish the changes, but your updates are here:
https://package.elm-lang.org/packages/ryannhg/date-format/2.3.0

Great work, and congratulations on your first Elm package contribution!

You did an excellent job, and I'm very grateful 😄 

Thanks again,
Ryan

**Pull request merged**
